### ISSUE TITLE
Container doesn't work when built using dockerfile instructions at "docs/tutorial/our-application/index.md:[lines40-44]"

### ISSUE THREAD

**Issue by tongilsoft** [docker/getting-started#121]
Container doesn't keep running and in the Docker dashboard:logs section we can see:

> `internal/modules/cjs/loader.js:818`
> `throw err;`
> `^`
> `Error: Cannot find module '/app/src/index.js'`
> `at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)`
> `at Function.Module._load (internal/modules/cjs/loader.js:667:27)`
> `at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)`
> `at internal/main/run_main_module.js:17:47 {`
> `code: 'MODULE_NOT_FOUND',`
> `requireStack: []`
> `}`

after some work, I dicovered the problem is about dockerfile instruction commands at "docs/tutorial/our-application/index.md"

**In line 42 we have:**
> `COPY . . ` _//this causes the path to 'index.js' to be '/app/app/src/index.js' resulting into node not founding file to be executed as expected by the command ENTRYPOINT ["node","src/index.js"] at line 44_

**I changed that by (and container works perfectly):**
> `COPY . /` _//this fixes the path to 'index.js' to be '/app/src/index.js' as expected by the command ENTRYPOINT ["node","src/index.js"] at line 44_

**So, my proposal to fix this issue is:**
just change line 42 at "docs/tutorial/our-application/index.md" as proposed above.

**Why?**
Is so frustrating for a newby (like me) when it supposes the instructions you should learn from, doesn't work and you ask yourself: _what I did wrong?_

**Comment by mikesir87** [comment]
We're sorry to hear about the struggles you had and that it took so long for us to respond. We certainly don't what you to feel like you've done something wrong.

The tutorial has gone through many updates and iterations since the time you created this issue, many of which we anticipate resolves the struggles you had. Therefore, I'm going to go ahead and close this issue.

If you have any more struggles or feedback, please don't hesitate to reach out and let us know. Thanks!
