### ISSUE TITLE
The commands "docker exec" and "docker run -it" doesn't work on my terminal

### ISSUE THREAD

**Issue by longqua69** [docker/getting-started#127]
Hi Docker team,

In file: 

[get-started/05_persisting_data.md](https://docs.docker.com/get-started/05_persisting_data/), I have an issue that I don't know whether I've misunderstood the guideline or it's really an error.

1. I followed the guideline and it works when I tried the command on CLI (use cat command on CLI)

![Docker Guidline](https://user-images.githubusercontent.com/37626565/110214154-f2b4c880-7ed5-11eb-9e13-11c601ab595f.PNG)

2. About the remaining commands which I use on my local terminal.

![The first one](https://user-images.githubusercontent.com/37626565/110213483-d4999900-7ed2-11eb-8420-4665d850ccb0.PNG)

![The 2nd one](https://user-images.githubusercontent.com/37626565/110214294-88e8ee80-7ed6-11eb-8116-b044bda711d2.PNG)

It looks like Docker didn't see the ubuntu images on my local machine when I didn't map the ports from the host, right?

Please help me to fix this error.

Thanks & Best regards,

Anh Tran

**Comment by mikesir87** [comment]
Hi @longqua69! 👋  Thanks for opening an issue and apologies for the delay in getting back to you. We recognize this issue is quite old, so you most likely moved on a long time ago. Both our guide and Docker Desktop have improved a lot since then, many of which changes have hopefully resolved the issue you were experiencing. Therefore, we're going to go ahead and close out this issue. 

If you're still having issues, feel free to create a new issue and we can help you out going forward.
