### ISSUE TITLE
"Part 6: Use bind mounts" - nodemon not responding to changes

### ISSUE THREAD

**Issue by avery-whitehead** [docker/getting-started#154]
Hiya,

I was following the tutorial on bind mounts and nodemon wasn't recognising changes made on my host machine. The tutorial to set up the bind mount worked perfectly, the changes were being saved in the container too, but nodemon wasn't picking them up.

After some digging I found instructions in the nodemon README that suggest to use the `-L` flag when using containers, but only as a last resort. https://github.com/remy/nodemon#application-isnt-restarting

Adding the `-L` flag to the dev script in `package.json` and recreating the container works fine and I can carry on the tutorial as normal, but I'm wondering if a recent change to something broke this because I can't find this issue with the Docker tutorial mentioned anywhere else. Has this been a known issue in the past with a different workaround?

**Comment by mikesir87** [comment]
Hi there! Thanks for submitting an issue and apologies for the long delay in responding to you.

Due to recent upgrades of the project and Docker Desktop, this appears to not be an issue anymore. But, if you or others are running into it again, feel free to create a new issue and we'll be happy to dive in again and update as needed.

**Comment by tbaiense** [comment]
I encountered the same issue (although it was fixed by adding the `-L` ) only when running  the container with the bind mount using Docker Desktop for Windows (Docker 28.3.2) through WSL2. Tested the same container on MacOS 15 (also on Docker version 28.3.2) but wasn't able to reproduce the issue. 

The bind path was specified relatively, but the full path on Windows has whitespace (`C:\Users\vhps1\OneDrive\Área de Trabalho\appName\docker`). Could this be the cause?
