### ISSUE TITLE
nodemon stuck at starting `node src/index.js` when running `docker-compose`

### ISSUE THREAD

**Issue by lagset** [docker/getting-started#167]
Hi there,

I am just doing the tutorial part _Using Docker Compose_ on Windows 10 21H1 with Docker Desktop and just wanted to note the following:

After adding the `docker-compose.yml ` file into the `app` directory and running `docker-compose up -d` the app service is stuck on ``[nodemon] starting `node src/index.js` ``, thus I can not access the app on `http://localhost:3000`. This are the most recent lines of the app_1 log:

```
app_1    | yarn install v1.22.5
app_1    | [1/4] Resolving packages...
app_1    | success Already up-to-date.
app_1    | Done in 0.60s.
app_1    | yarn run v1.22.5
app_1    | $ nodemon src/index.js
app_1    | [nodemon] 1.19.4
app_1    | [nodemon] to restart at any time, enter `rs`
app_1    | [nodemon] watching dir(s): *.*
app_1    | [nodemon] watching extensions: js,mjs,json
app_1    | [nodemon] starting `node src/index.js`
```

Until then, everything worked well, even running the `app` and the `mysql `container manually, as described in the part _Multi-Container Apps_. 

[This issue](https://github.com/docker/getting-started/issues/86) seems related, but since it's old and a pita to scroll down I opened a new one.

**Comment by mikesir87** [comment]
Apologies for the delay in responding to your issue. 

Funny enough, I ran into a similar situation yesterday when working with someone. In their case, they had a typo in the name of the mysql service, which was causing DNS resolution to fail. But, there was code waiting for the database to be ready during the server startup. Since it never resolved (and there was no timeout), it appeared to be hung. The recently merged PR (#331) resolves this. If you still have issues, feel free to open a new issue and we'll be happy to help out!
