### ISSUE TITLE
The Dockerfile throws an error 

### ISSUE THREAD

**Issue by omrastogi** [docker/getting-started#200]
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/app/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Even though the file are in correct orders. I am getting this error. 
What may be the reason for this 
How should I fix this error.

**Comment by agustintosco** [comment]
Hi, I am getting the same error. I cannot find what could it be the problem. Did you find a solution?

**Comment by luxuwin** [comment]
any update on this?

**Comment by mikesir87** [comment]
Hi all! 👋 Thanks for opening an issue and apologies for the delay in getting back to you. We recognize this issue is fairly old, so you all have most likely moved on a long time ago. Both our guide and Docker Desktop have improved a lot since then, many of which changes have hopefully resolved the issue you were experiencing. Therefore, we're going to go ahead and close out this issue.

If you're still having issues, feel free to create a new issue and we can help you out going forward.
