### ISSUE TITLE
Why run tail -f /dev/null to keep the container running?

### ISSUE THREAD

**Issue by krave1986** [docker/getting-started#201]
Hi, everyone!

Thank you so much for providing such a great tutorial!
It helps me to learn docker much easier!

I have a question though.
In 5th section - Persisting our DB, we have this command to start a container and create a file with a random number.
```
docker run -d ubuntu bash -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"
```

But I don't see the reason why we need to run `tail -f /dev/null` to keep the container running.
Could you please give some hints about this?

Thank you and have a great day!

**Comment by vignemail1** [comment]
Without this additional command, when the `shuf` command is finished, the container will stop. 
With it, the container will remain idle, which makes it easier to connect to it later (`docker exec -it container_name bash`).

`tail -f /dev/null` is a command that runs endlessly and doesn't use any CPU because nothing can be read from `/dev/null` and we are asking for an endless read from it.

**Comment by mikesir87** [comment]
Thanks @krave1986 for asking the question and @vignemail1 for answering! Apologies for the delayed on our end too. As was mentioned, that is the case... we just need a command that will keep the container up and running. Once the main process exits, the container stops as well. 

Since this question is answered, I'm going to go ahead and close this issue. If you have any further questions, feel free to start a new issue and we'll be faster to respond! 😄
