### ISSUE TITLE
M1 Mac issue during Sharing our App step

### ISSUE THREAD

**Issue by hyunjong-park** [docker/getting-started#260]
I was following the getting-started guide step by step using M1 macbook.

When following Sharing our App section, pulling the pushed image from m1 macbook causes and error on play with docker environment since the image on the local image is for arm64 while the play with docker is running on amd64.

This will create confusion to the first users of docker using m1 macbook. 

I think there should be some notification for the beginners with m1 macbook regarding this issue in previous sections so that  they can build an image for amd64 before pushing it on the docker hub.

**Comment by ben519** [comment]
For others facing this issue,

1. Rebuild the image locally, like this

```
docker build --platform linux/amd64 -t getting-started .
```

2. Add the tag

```
docker tag getting-started <your-username>/getting-started   
```

3. Pull the updated image inside of Play With Docker

```
docker pull <your-username>/getting-started
```

**Comment by mikesir87** [comment]
Hi all and apologies for the delayed response. The docs have been updated to reflect the usage of the `--platform` option to ensure the application works in Play with Docker when compiled on Apple Silicon machines.

@newearthmartin To explain it, the Dockerfile is used to provide the instructions on how to build the container image itself. So, when pushing to Hub, you are pushing the image that was described by the Dockerfile. The reason we have to provide the platform is because binary code is compiled for a specific architecture (Intel vs ARM). When building by default on an Apple Silicon machine, it will use the `linux/arm64` architecture. That means the image can only run on machines that can understand that architecture. If I want the code to run on multiple architectures, then yes! I have to build for multiple architectures. Hope that helps!

I'm going to go ahead and close this issue as there's no remaining issue here. But, feel free to comment/keep the conversation going if needed.

**Comment by chris-sloan** [comment]
I followed the instructions once more to create a separate `amd` specific repository.

`docker tag getting-started-amd <your-username>/getting-started-amd`

Then used this repository to 'play' with.

**Comment by IwfWcf** [comment]
@mikesir87 I don't see the update in docs, I still need to search and find this issue to solve it

**Comment by IwfWcf** [comment]
@mikesir87 Can you update the tutorial build from docker/getting-started too?
