### ISSUE TITLE
First Step Getting Started docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF.

### ISSUE THREAD

**Issue by luisurbinanet** [docker/getting-started#275]
Hi
I'm installing Docker Desktop on my machine Windows 10 Pro v:21H2 19044.1645 with CPU i7-7700 and 16Gb ram.
When I try to follow first tutorial I get this error on powershell embeded
```
PS C:\Users\luisu> docker run --name repo alpine/git clone https://github.com/docker/getting-started.git
Unable to find image 'alpine/git:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": EOF.
See 'docker run --help'.
PS C:\Users\luisu> docker cp repo:/git/getting-started/ .
Error: No such container:path: repo:/git/getting-started/
PS C:\Users\luisu>
```

Second: When I try to login making clic on Sing In Button, I get an error
```
Login failed
Post "https://login.docker.com/oauth/token": read tcp 192.168.1.3:57197->104.16.171.253:443: wsarecv: Se ha anulado una conexión establecida por el software en su equipo host..
```
And I couldn't download a container for Ubuntu neither browse a containers available using my personal account.

Could anybody help with it to find which is the error? thanks.

**Comment by mikesir87** [comment]
Hi all! 👋  Thanks for opening an issue and apologies for the delay in getting back to you. We recognize this issue is fairly old, so you all have most likely moved on a long time ago. Both our guide and Docker Desktop have improved a lot since then, many of which changes have hopefully resolved the issue you were experiencing. Therefore, we're going to go ahead and close out this issue. 

If you're still having issues, feel free to create a new issue and we can help you out going forward.
