### ISSUE TITLE
Problem completing "Bind Mounts" section of this tutorial

### ISSUE THREAD

**Issue by Just4lol** [docker/getting-started#64]
Hello, I have followed this tutorial to this part with no problem but, I can't run the command for starting a Dev-Mode container: 
_Run the following command (replace the \ characters with \` in Windows PowerShell). We'll explain what's going on afterwards:_
`docker run -dp 3000:3000 \
    -w /app -v ${PWD}:/app \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"`

What I have tested: 
![image](https://user-images.githubusercontent.com/23459938/85915836-0113f600-b819-11ea-8c83-33756d43cd34.png)

Without the tick **\`** I get an error stack: 
![image](https://user-images.githubusercontent.com/23459938/85915864-3ddfed00-b819-11ea-808e-bb4d701b590b.png)

Did I miss understood something? Thank you in advance.

**Comment by Just4lol** [comment]
So, I have read through the doc and saw: _The File sharing tab is only available in Hyper-V mode, because in WSL 2 mode and Windows container mode all files are automatically shared by Windows._

As I have done Android dev and had to enable Hyper-V to emulate I had to add the dir I was working in Setting->Resources->File Sharing. After that, the first command worked. 

Now, I find both errors are not clear; invalid syntax nor that big stack trace (well. the only clue I find useful is Filesharing has been canceled)  and the tutorial don't mention this. Maybe this is worth mentioning in the tutorial and maybe the guys working on docker could do something about the errors.

**Comment by StefanScherer** [comment]
Thanks @Just4lol for the screenshots.
Oh, maybe we have to explain how the PowerShell command really looks like instead of letting you try how that works. The first screenshot has backticks, but I assume they must be separated with a space, in your first try this leads to a weird command and then `-c` gets interpreted by the Docker CLI and not by the `sh` command inside the container.
We should improve the tutorial to give you copy-pastable Windows variantes of this commands.

The second try shows you a message as you already found out. I agree, the stack trace isn't necessary here and we should at least give a hint that the file sharing must be enabled when using Hyper-V backend.

**Comment by Just4lol** [comment]
I have to add that, I did not know that in Powershell you could use **[space]`[enter]** to write your command on new lines as well as \ for Linux. I would have removed a part of the confusion for me :)

**Comment by Jeffersontee** [comment]
Hello I put in the notepad replace \ with `and copy and paste. Use Docker Desktop windows 10 pro

docker run -dp 3000:3000 `
    -w /app -v ${PWD}:/app `
    node:12-alpine `
    sh -c "yarn install && yarn run dev"

**Comment by StefanScherer** [comment]
I've opened #70 to show the PowerShell commands as well. This makes it easier to copy-paste the commands.
