### ISSUE TITLE
Problem completing "Bind Mounts" section of this tutorial

### ISSUE THREAD

**Issue by AnWaTr** [docker/getting-started#7]
Hello!  I am very much enjoying learning docker through this getting-started tutorial. However, I am having problems completing the Bind Mounts section.  It seems the following command is invalid (what is the $PWD doing?):

```
docker run -dp 3000:3000 \
    -w /app -v $PWD:/app \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"

```
Also, there do not seem to be full front to back steps on what to do after running this command (which causes an error on my terminal session):

`docker: invalid reference format: repository name must be lowercase.`

If someone could look into this that would be great - because I've already learned a lot in the first several steps!  

Thank you much -
Andrew

**Comment by mikesir87** [comment]
Hello Andrew and welcome to Docker! I’m sorry to hear that you’re having trouble, but happy to help!

When creating bind mounts, you need two things... 1) the source of the mount and 2) the target of the mount. The source is typically a directory or file on the host and the target is where in the container that source should be made available.

The `$PWD` piece is basically saying “the current directory.” For example, if you run (in your cli) `echo $PWD`, you should get the full path to the current directory.

The specific error you’re getting is typically seen when someone types in a `docker run` but is missing one of the flags. For example, if I ran `docker run 80:80 nginx` (missing the `-p` in front of `80:80`), the run command is going to think the `80:80` is the image name, since there is no flag in front of it. That obviously won’t resolve and will cause an error. So, the first thing to look at is to make sure you’re typing the command _exactly_ right.

If you’ve verified that and you’re still having trouble, I’ll need a little more info. If you could take a screenshot of the command and the error you’re seeing and attach it here, that would be awesome. Secondly, are you running Docker Desktop on Mac or Windows?

**Comment by mjlumley** [comment]
On powershell I could get the command running only changing from $PWD to ${PWD}. Anything else, it either silently fails or complains with an error.

**Comment by mikesir87** [comment]
Took a little while, but made the update @mjlumley to the tutorial. If this doesn't solve the original issue @AnWaTr, feel free to comment.

**Comment by zqcccc** [comment]
![image](https://user-images.githubusercontent.com/19168323/81550420-c7934280-93b2-11ea-8d56-1003ff412f8c.png)

When I run the command in the "Bind Mounts" section of this tutorial, it occurred errors. What should I do?

**Comment by SeriousLee13** [comment]
The only way I could get this section "working" - not sure if it _actually_ works yet, just that it returned a container id, and didn't throw an error - was by turning the command into a one-liner. From:

`docker run -dp 3000:3000 \
    -w /app -v ${PWD}:/app \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"`

To:

`docker run -dp 3000:3000 -w /app -v ${PWD}:/app node:12-alpine sh -c "yarn install && yarn run dev"`

Every time I tried to run it as-is in the tutorial, it'd throw a whole bunch of errors about terms not recognized. I'm using docker desktop on windows with powershell.

Hope this helps someone 😊

**Comment by zqcccc** [comment]
Thanks! It works!

> The only way I could get this section "working" - not sure if it _actually_ works yet, just that it returned a container id, and didn't throw an error - was by turning the command into a one-liner. From:
> 
> ```
> docker run -dp 3000:3000 \
>     -w /app -v ${PWD}:/app \
>     node:12-alpine \
>     sh -c "yarn install && yarn run dev"
> ```
> 
> To:
> 
> `docker run -dp 3000:3000 -w /app -v ${PWD}:/app node:12-alpine sh -c "yarn install && yarn run dev"`
> 
> Every time I tried to run it as-is in the tutorial, it'd throw a whole bunch of errors about terms not recognized. I'm using docker desktop on windows with powershell.
> 
> Hope this helps someone 😊

**Comment by stetogias** [comment]
I'd just like to leave this here as a comment for anyone having a problem

If you run the command outside the app directory it returns and ID, throws no errors but the container is not running.
docker ps returns nothing. It would be nice to have this stated in the tutorial.

tried it on linux (Pop!_os) as a non-root user

**Comment by tiagoheras** [comment]
Hello! I'm trying to complete this step of the tutorial but I run into an error when I try to run this code... 
`docker run -dp 3000:3000 \
    -w /app -v "$(pwd):/app" \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"`
It gives me the following error...
![image](https://user-images.githubusercontent.com/65797374/96390416-ed571b80-118a-11eb-9ced-472c1ce4c644.png)
I tried writing the command within a single line but it didn't work either.
If somebody has an idea of what could be happening it would be great since I don't know what else to do.

**Comment by StaffanFalk** [comment]
There are several problems, and it took some time for me to understand.
However; to use bind mounts for Docker under Windows, you need to enable file sharing for the directory you want to mount.

In Docker Desktop: Click on the Settings icon->Resources->File Sharing.
Add a directory which contains your share point. In my case, I shared C:\ (probably a bit dangerous, but it worked).
After that, the command will work. I choose to avoid line breaks to avoid trouble:

docker run -dp 3000:3000     -w /app -v "${PWD}:/app"     node:12-alpine     sh -c "yarn install && yarn run dev"

Note that there shall be curly brackets around PWD, not ordinary ones.

Good luck!

**Comment by johanperjulius1** [comment]
Hi! Like the previous I love the tutorial but I have issue with this section.

I am on Ubuntu 20.04 and using zsh as a shell.
I am in root folder (everything this far worked fine when working in root folder but let me know if this is wrong)

I run the command: 
`sudo docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"`
     
     and I was thinking sh -c is for bash so I also tried replacing it with zsh -c but end result is the same.

When I run the command everything works BUT the container immediatly stops running. I run 
`sudo docker logs <container_id>`

    and receive back this in the command line:
    
    `yarn install v1.22.5
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Package "casino-api-netrefer" refers to a non-existing file '"/app/casino-api-netrefer"'`
      
      
      which is a completely unrelated project that I have even removed from my computer.
      What can I do?
      
      Any help is greatly appreciated.

**Comment by Stacy-Sanders** [comment]
I'm having the same issues. The ordinary parenthesis are still in the code, not the curly. 

I finally was able to run it without an error when I changed to the curly braces and a new container was made, but my container wouldn't stay running. When I checked out the container it stated package.json was not in the folder. The tutorial states to run the command from the src code folder. 

I went back to the app folder and ran the code from there. Container is made and running and browser finally works.

Hopefully this helps someone else too!
