### ISSUE TITLE
Host in volume?

### ISSUE THREAD

**Issue by jaydarius** [docker/getting-started#80]
In the "Persisting our Todo Data" section:
> By creating a volume and attaching (often called "mounting") it to the directory the data is stored in, we can persist the data. As our container writes to the todo.db file, it will be persisted to the host in the volume.

I'm confused by the last few words.  It seems to me that you are saying the host has been or will continue to be in the volume.

Do you mean to instead say something like:
> When our container writes to the todo.db file and is subsequently stopped, this file will be persisted via the volume to the host.

**Comment by mikesir87** [comment]
Hi @jaydarius! Apologies for the _looong_ delay in responding to your question.

When we say "it will be persisted to the host in the volume", you are correct in that the file is being persisted on the host because of the volume setup/config. 

In this case, since we are using a "named volume", you can think of the volume as merely a bucket/location that files will be persisted. So, since we aren't using bind mounts but an actual volume, the terminology still makes sense that the file is saved in the volume. But, I can see how it can be a little confusing. Hope that helps though!

I'm going to go ahead and close this issue, but feel free to keep the conversation going if you have follow-up questions. Thanks!
