### ISSUE TITLE
Bind mount syntax - different than docs

### ISSUE THREAD

**Issue by jaydarius** [docker/getting-started#83]
http://localhost/tutorial/using-bind-mounts/
In the "Starting a Dev Mode Container" section, the bind mount uses quotes around the source and target paths:
> `-v "$(pwd):/app"` - bind mount the current directory from the host in the container into the /app directory

However, in https://docs.docker.com/storage/bind-mounts/, see that the quotes are only around the source path:
![image](https://user-images.githubusercontent.com/31786606/91642058-e2cf9f80-e9ed-11ea-9cb4-079a3a7e024f.png)

**Comment by jumile** [comment]
Is your issue about document consistency, or does it break things? I'd have thought `"$(pwd)/foo:/bar"`, `"$(pwd)"/foo:/bar` or `"$(pwd)/foo:/bar"` (presumably to catch any whitespace, etc) would result in the same, though I may be mistaken.

I ran into an issue at this point while running the tutorial on Windows command line, as the first argument assumes a Linux shell. I was able to resolve it using Windows path naming for that field, e.g.: `-v "D:\somedirectory\app":/app` (using `-v "D:\somedirectory\app:/app"` also works).

**Comment by ArturoBa** [comment]
Thanks @jumile, finally I could solve the problem. The logs in the container kept saying that it "couldn't find the package.json in the /app directory". It seems, as you said that the first argument assumes a Linux shell, while I'm running the cmd on Windows. I had to enter the absolute path ("C:\my-directory\blabla\app") to get it work. Thanks for your help!

**Comment by mikesir87** [comment]
Hi all! Apologies for the delay in responding to this issue. The tutorial has gone through several improvements since this issue was created, some of which I anticipate would have resolved this issue. Therefore, I'm going to go ahead and close it.

If you have future questions or issues, feel free to create a new issue and we'll be happy to help out (and will respond much more quickly too!). Thanks all!
