### ISSUE TITLE
Bind Mount Command not working

### ISSUE THREAD

**Issue by Jameshgreen95** [docker/getting-started#84]
Running the command: 

`docker run -dp 3000:3000 \
    -w /app -v "$(pwd):/app" \
    node:12-alpine \
    sh -c "yarn install && yarn run dev"`

Yields the response:

`docker: Error response from daemon: the working directory 'C:/Program Files/Git/app' is invalid, it needs to be an absolute path.`

I don't really understand why it is defaulting to the Git directory. 

When running the pwd command it does return the correct directory. Any ideas?

**Comment by brunoadamalves** [comment]
Hey, try this:

docker run -dp 3000:3000      -w /app -v "/$(pwd):/app"      node:12-alpine      sh -c "cd /$(pwd) && yarn install && yarn run dev"

**Comment by bcollin** [comment]
I am not sure Windows knows about he pwd command. I used %cd% instead.

**Comment by MadPigeon** [comment]
I tried both solutions with `%cd`but that didn't fix the issue for me.
I have git bash, I think that's the reason it tries to search from that location.

**Comment by mikesir87** [comment]
Hi all! Apologies for the delay in responding to this issue. The tutorial has gone through several improvements since this issue was created, some of which I anticipate would have resolved this issue. Therefore, I'm going to go ahead and close it.

If you have future questions or issues, feel free to create a new issue and we'll be happy to help out (and will respond much more quickly too!). Thanks all!

**Comment by parthmern** [comment]
tell me the command i have windows machine

windows src:

D:\Z_PARTH-CODES\docker\07_volume

so what to do how to get HOST path
