### ISSUE TITLE
Step 7. Multi-Container Apps -> Unable to run App with MySQL!

### ISSUE THREAD

**Issue by Alex-Moh** [docker/getting-started#97]
- [ ] 5 hours of searching with no results.

- [ ] Diagnostic ID: 9EDF4AAE-B34A-4996-9BE0-D4D6310E18D4/202010140151

40
When I enter the following command on windows cmd:
`docker run -dp 3000:3000 ^
  -w /app -v "cd:/app" ^
  --network todo-app ^
  -e MYSQL_HOST=mysql ^
  -e MYSQL_USER=root ^
  -e MYSQL_PASSWORD=secret ^
  -e MYSQL_DB=todos ^
  node:12-alpine ^
  sh -c "yarn install && yarn run dev"`

**The CMD returns:**
`9165fe85fbd4c98b9f9455509081252fa89f8f6e072e6caa2651b5a062bc8927
docker: Error response from daemon: driver failed programming external connectivity on endpoint pensive_meitner (97c005c64c2f6ab1dabb8106a3b57285ba610717b36fd3ec82f1c97ad7efa648): Bind for 0.0.0.0:3000 failed: port is already allocated.`
[StackOverFlow](https://stackoverflow.com/questions/64345362/connecting-dockerized-app-to-mysql-using-windows-command-returns-error)

**Comment by youngDevOps** [comment]
The Port has already been allocated and in use. Try and check Docker Desktop and see if any other containers are running. If so stop them and it should work. I had a similar issue.

**Comment by mikesir87** [comment]
Hi all! Apologies on the looong delay to respond to your issue. As @youngDevOps mentioned, you have a port conflict going on here, meaning you have another container that was running and using port 3000.

Since this question has been answered (and it's very old), I'm going to go ahead and close this issue.

If you have future questions or issues, feel free to create a new issue and we'll be happy to help out (and will respond much more quickly too!). Thanks all!
